### ISSUE TITLE
Meet the RuntimeError when i try different size of images 

### ISSUE THREAD

**Issue by GH-lhc** [AAleka/Transformer-Cycle-GAN#4]
Hi, when i try different size of images(512*256), there are a RuntimeError:
D:\Anaconda3\envs\srcgan\lib\site-packages\torch\nn\modules\loss.py:96: UserWarning: Using a target size (torch.Size([1, 3, 512, 256])) that is different to the input size (torch.Size([1, 3, 256, 512])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.l1_loss(input, target, reduction=self.reduction)
  0%|          | 0/2114 [00:15<?, ?it/s]
Traceback (most recent call last):
  File "F:\LHC\algrithm_2023_11\Transformer-Cycle-GAN-main\Train.py", line 184, in <module>
    main()
  File "F:\LHC\algrithm_2023_11\Transformer-Cycle-GAN-main\Train.py", line 144, in main
    train_fn(disc_A, disc_B, gen_A, gen_B, loader, opt_disc, opt_gen, L1, mse, d_scaler, g_scaler, epoch)
  File "F:\LHC\algrithm_2023_11\Transformer-Cycle-GAN-main\Train.py", line 59, in train_fn
    cycle_b_loss = l1(b, cycle_b)
  File "D:\Anaconda3\envs\srcgan\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Anaconda3\envs\srcgan\lib\site-packages\torch\nn\modules\loss.py", line 96, in forward
    return F.l1_loss(input, target, reduction=self.reduction)
  File "D:\Anaconda3\envs\srcgan\lib\site-packages\torch\nn\functional.py", line 3248, in l1_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "D:\Anaconda3\envs\srcgan\lib\site-packages\torch\functional.py", line 73, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 3
I'm so sorry to bother you again.

**Comment by AAleka** [comment]
My bad, forgot the order of dimensions in PyTorch. Fixed the Train.py and Model.py, should work fine now. Thanks for letting me know again! Might close the issue if the problem was solved.

**Comment by GH-lhc** [comment]
@AAleka It's work! thank you very much.
